# cloudbuild.yaml
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/image-search', '.']
    
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/image-search']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'image-search'
      - '--image=gcr.io/$PROJECT_ID/image-search'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--set-env-vars=GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'
      - '--max-instances=29'

# Set environment variables
substitutions:
  _GCS_BUCKET_NAME: your-bucket-name

# Set timeout for the build
timeout: 1200s

# Specify images to push to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/image-search'
